# Generated by Django 5.1.2 on 2024-10-17 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('calorias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('Vegetariano', 'Vegetariano'), ('No Vegetariano', 'No Vegetariano'), ('Vegano', 'Vegano'), ('Otro', 'Otro')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Personal', 'Personal'), ('Administrador', 'Administrador')], max_length=15)),
                ('preferencias_alimenticias', models.TextField(blank=True, null=True)),
                ('restricciones_dieteticas', models.TextField(blank=True, null=True)),
                ('habitos_consumo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartaComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carta')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], max_length=15)),
                ('cantidad', models.IntegerField(default=1)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Stripe', 'Stripe'), ('PayPal', 'PayPal'), ('Otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Fallido', 'Fallido')], max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField()),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
