# Generated by Django 5.1 on 2024-10-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reserva_codigo_reserva_reserva_fecha_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.carta'),
        ),
    ]
