# Generated by Django 5.1 on 2024-10-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_pedido_carta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='comidas',
        ),
    ]
