# Generated by Django 5.1 on 2024-11-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_cartacomida_carta_alter_cartacomida_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Pagado', 'Pagado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Reservado', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reserva'),
        ),
    ]
