# Generated by Django 5.1 on 2024-11-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_pedido_estado_alter_pedido_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.CreateModel(
            name='PedidoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_comidas_rel', to='api.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_comidas',
            field=models.ManyToManyField(through='api.PedidoComida', to='api.comida'),
        ),
    ]
