# Generated by Django 5.1 on 2024-11-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_pedido_cantidad_pedidocomida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='retroalimentacion',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='pedidocomida',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_comidas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='pedidocomida',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='api.categoria'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.pedido'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('calificacion_promedio', models.FloatField(default=0)),
                ('votos', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='CartaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartaitem_set', to='api.carta')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartaitem_set', to='api.item')),
            ],
        ),
        migrations.AddField(
            model_name='retroalimentacion',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoitem_set', to='api.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_items',
            field=models.ManyToManyField(through='api.PedidoItem', to='api.item'),
        ),
        migrations.CreateModel(
            name='ReservaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaitem_set', to='api.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_items',
            field=models.ManyToManyField(through='api.ReservaItem', to='api.item'),
        ),
        migrations.DeleteModel(
            name='CartaComida',
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.DeleteModel(
            name='PedidoComida',
        ),
    ]
