# Generated by Django 5.1 on 2024-11-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_comida_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='parent',
        ),
    ]
