# Generated by Django 5.1 on 2024-11-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_categoria_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaitem',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carta_items', to='api.carta'),
        ),
        migrations.AlterField(
            model_name='cartaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carta_items', to='api.item'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_item_relations', to='api.item'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_item_relations', to='api.pedido'),
        ),
        migrations.AlterField(
            model_name='reservaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_item_relations', to='api.item'),
        ),
        migrations.AlterField(
            model_name='reservaitem',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_item_relations', to='api.reserva'),
        ),
    ]
