# Generated by Django 5.1 on 2024-11-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_cartaitem_carta_alter_cartaitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reserva_relations', to='api.item'),
        ),
        migrations.AlterField(
            model_name='reservaitem',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_items_relations', to='api.reserva'),
        ),
    ]
