# Generated by Django 5.1 on 2024-11-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_reservaitem_item_alter_reservaitem_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reservas_relations', to='api.item'),
        ),
    ]
