# Generated by Django 5.1 on 2024-11-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_pedido_pedido_items_alter_pedidoitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_in_cartas', to='api.item'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_items',
            field=models.ManyToManyField(related_name='pedidos', through='api.PedidoItem', to='api.item'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reserva_items',
            field=models.ManyToManyField(related_name='reservas', through='api.ReservaItem', to='api.item'),
        ),
        migrations.AlterField(
            model_name='reservaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reservas', to='api.item'),
        ),
    ]
