# Generated by Django 5.1 on 2024-11-04 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='api.reserva'),
        ),
    ]
