# Generated by Django 5.1 on 2024-11-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_pedido_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='calificacion_promedio',
        ),
        migrations.RemoveField(
            model_name='item',
            name='votos',
        ),
        migrations.AddField(
            model_name='item',
            name='carbohidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='grasas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
