# Generated by Django 5.1 on 2024-12-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_item_calificacion_promedio_remove_item_votos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
